[package]
name = "cargo-basic"
version = "0.1.0"
authors = ["Deepak <sah.sslpu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shell-words = "0.1.0"
dirs = "2.0"
